import { DefaultTheme } from 'react-native-paper'
import { colors } from './colors'
import { spacers, layout } from './constants'
import { statusBarHeight } from '../utils/device'

const theme = {
  ...DefaultTheme,
  roundness: 2,
  colors: {
    ...DefaultTheme.colors,
    ...colors,
  },
}

// TODO: There is a better way to create this with a function and arrays
const paddings = {
  statusBarPadding: {
    paddingTop: statusBarHeight(),
  },
  p0: { padding: spacers.spaceLv0 },
  px0: { paddingHorizontal: spacers.spaceLv0 },
  py0: { paddingVertical: spacers.spaceLv0 },
  pt0: { paddingTop: spacers.spaceLv0 },
  pb0: { paddingBottom: spacers.spaceLv0 },
  pl0: { paddingLeft: spacers.spaceLv0 },
  pr0: { paddingRight: spacers.spaceLv0 },
  p1: { padding: spacers.spaceLv1 },
  px1: { paddingHorizontal: spacers.spaceLv1 },
  py1: { paddingVertical: spacers.spaceLv1 },
  pt1: { paddingTop: spacers.spaceLv1 },
  pb1: { paddingBottom: spacers.spaceLv1 },
  pl1: { paddingLeft: spacers.spaceLv1 },
  pr1: { paddingRight: spacers.spaceLv1 },
  p2: { padding: spacers.spaceLv2 },
  px2: { paddingHorizontal: spacers.spaceLv2 },
  py2: { paddingVertical: spacers.spaceLv2 },
  pt2: { paddingTop: spacers.spaceLv2 },
  pb2: { paddingBottom: spacers.spaceLv2 },
  pl2: { paddingLeft: spacers.spaceLv2 },
  pr2: { paddingRight: spacers.spaceLv2 },
  p3: { padding: spacers.spaceLv3 },
  px3: { paddingHorizontal: spacers.spaceLv3 },
  py3: { paddingVertical: spacers.spaceLv3 },
  pt3: { paddingTop: spacers.spaceLv3 },
  pb3: { paddingBottom: spacers.spaceLv3 },
  pl3: { paddingLeft: spacers.spaceLv3 },
  pr3: { paddingRight: spacers.spaceLv3 },
  p4: { padding: spacers.spaceLv4 },
  px4: { paddingHorizontal: spacers.spaceLv4 },
  py4: { paddingVertical: spacers.spaceLv4 },
  pt4: { paddingTop: spacers.spaceLv4 },
  pb4: { paddingBottom: spacers.spaceLv4 },
  pl4: { paddingLeft: spacers.spaceLv4 },
  pr4: { paddingRight: spacers.spaceLv4 },
  p5: { padding: spacers.spaceLv5 },
  px5: { paddingHorizontal: spacers.spaceLv5 },
  py5: { paddingVertical: spacers.spaceLv5 },
  pt5: { paddingTop: spacers.spaceLv5 },
  pb5: { paddingBottom: spacers.spaceLv5 },
  pl5: { paddingLeft: spacers.spaceLv5 },
  pr5: { paddingRight: spacers.spaceLv5 },
  p6: { padding: spacers.spaceLv6 },
  px6: { paddingHorizontal: spacers.spaceLv6 },
  py6: { paddingVertical: spacers.spaceLv6 },
  pt6: { paddingTop: spacers.spaceLv6 },
  pb6: { paddingBottom: spacers.spaceLv6 },
  pl6: { paddingLeft: spacers.spaceLv6 },
  pr6: { paddingRight: spacers.spaceLv6 },
}

const margins = {
  statusBarMargin: {
    marginTop: statusBarHeight(),
  },
  m0: { margin: spacers.spaceLv0 },
  mx0: { marginHorizontal: spacers.spaceLv0 },
  my0: { marginVertical: spacers.spaceLv0 },
  mt0: { marginTop: spacers.spaceLv0 },
  mb0: { marginBottom: spacers.spaceLv0 },
  ml0: { marginLeft: spacers.spaceLv0 },
  mr0: { marginRight: spacers.spaceLv0 },
  m1: { margin: spacers.spaceLv1 },
  mx1: { marginHorizontal: spacers.spaceLv1 },
  my1: { marginVertical: spacers.spaceLv1 },
  mt1: { marginTop: spacers.spaceLv1 },
  mb1: { marginBottom: spacers.spaceLv1 },
  ml1: { marginLeft: spacers.spaceLv1 },
  mr1: { marginRight: spacers.spaceLv1 },
  m2: { margin: spacers.spaceLv2 },
  mx2: { marginHorizontal: spacers.spaceLv2 },
  my2: { marginVertical: spacers.spaceLv2 },
  mt2: { marginTop: spacers.spaceLv2 },
  mb2: { marginBottom: spacers.spaceLv2 },
  ml2: { marginLeft: spacers.spaceLv2 },
  mr2: { marginRight: spacers.spaceLv2 },
  m3: { margin: spacers.spaceLv3 },
  mx3: { marginHorizontal: spacers.spaceLv3 },
  my3: { marginVertical: spacers.spaceLv3 },
  mt3: { marginTop: spacers.spaceLv3 },
  mb3: { marginBottom: spacers.spaceLv3 },
  ml3: { marginLeft: spacers.spaceLv3 },
  mr3: { marginRight: spacers.spaceLv3 },
  m4: { margin: spacers.spaceLv4 },
  mx4: { marginHorizontal: spacers.spaceLv4 },
  my4: { marginVertical: spacers.spaceLv4 },
  mt4: { marginTop: spacers.spaceLv4 },
  mb4: { marginBottom: spacers.spaceLv4 },
  ml4: { marginLeft: spacers.spaceLv4 },
  mr4: { marginRight: spacers.spaceLv4 },
  m5: { margin: spacers.spaceLv5 },
  mx5: { marginHorizontal: spacers.spaceLv5 },
  my5: { marginVertical: spacers.spaceLv5 },
  mt5: { marginTop: spacers.spaceLv5 },
  mb5: { marginBottom: spacers.spaceLv5 },
  ml5: { marginLeft: spacers.spaceLv5 },
  mr5: { marginRight: spacers.spaceLv5 },
  m6: { margin: spacers.spaceLv6 },
  mx6: { marginHorizontal: spacers.spaceLv6 },
  my6: { marginVertical: spacers.spaceLv6 },
  mt6: { marginTop: spacers.spaceLv6 },
  mb6: { marginBottom: spacers.spaceLv6 },
  ml6: { marginLeft: spacers.spaceLv6 },
  mr6: { marginRight: spacers.spaceLv6 },
}

export const sharedStyles = {
  ...paddings,
  ...margins,
  ...layout,
}

export default theme
